### ISSUE TITLE
Missing Copyright and Credits on Images

### ISSUE THREAD

**Issue by jaydeninniss** [ssupix/horizons-api#12]
### Description: 
Copyright and credit information are not displayed for images on the website.

### Steps To Reproduce:

1. Navigate to the Horizons website.
2. View any image.
3. Check for copyright information in the bottom left corner.

### Expected Result:
Copyright and credit details are visible for each image.

### Actual Result:
No copyright information is displayed for images somewhere on the card.

### Configuration:
Tested on a Macbook Pro 16"
Chromium Based Browser
December 6, 2024, 12:00pm

Severity: High
Priority: High
Type: Bug
Branch: development

**Comment by plries** [comment]
### Steps to Solve:
Added the copyright string to the `imageData.map` and displayed it as a chip on the bottom right of the card.

```
imageData.map((item, index) => (
  <Card
      className="col-span-1"
      key={index}
      title={item.title || "Untitled"}
      date={item.date || "Redacted"}
      copyright={item.copyright || "Unknown"}
      media_type={item.media_type || "Undefined"}
      explanation={item.explanation || 'No description available.'}
      url={item.url || ""}
  /> 
))
```
