### ISSUE TITLE
Website Not Responsive

### ISSUE THREAD

**Issue by jaydeninniss** [ssupix/horizons-api#13]
### Description: 
The website does not display correctly on devices other than desktops.

### Steps To Reproduce:

1. Navigate to the website.
2. View the site in mobile and tablet resolutions.
3. Use inspector to emulate if you do not have mobile devices

### Expected Result:
The website is optimized and responsive for all screen sizes.

### Actual Result:
The website is optimized and responsive for all screen sizes.

### Configuration:
Tested on a Macbook Pro 16"
Chromium Based Browser
December 6, 2024, 12:00pm

Severity: High
Priority: High
Type: Bug
Branch: development

**Comment by plries** [comment]
### Steps to Solve:
Added different `font-sizes` and `grid-columns` for tablet and mobile devices. This was done using `tailwind.config.js`, enabling `tablet:` and `mobile:` prefixes to act as media queries in the Tailwind classes.
```
screens: {
      desktop: { 'min': '1080px' },
      tablet: { 'min': '425px', 'max': '1080px' },
      mobile: { 'max': '425px' },
```
