### ISSUE TITLE
Lack of Metadata + No Custom Favicon

### ISSUE THREAD

**Issue by jaydeninniss** [ssupix/horizons-api#15]
### Description: 
The website lacks any metadata in the head for SEO or declaring a custom favicon.

### Steps To Reproduce:

1. Navigate to the website.
2. Notice the default React favicon on the tab.
OR
1. View the source code here: https://github.com/ssupix/horizons-api/blob/b036324e87c27ff52d730666493ef5035fa2f571/public/manifest.json

### Expected Result:
The favicon on the tab would show a custom icon. The page would include metadata in the head to improve SEO and improve visibility. 

### Actual Result:
There is no metadata in the head of the page and the favicon is the default React icon.

### Configuration:
Tested on a Macbook Pro 16"
Chromium Based Browser
December 6, 2024, 12:00pm

Severity: Medium
Priority: Medium
Type: Bug
Branch: development

**Comment by plries** [comment]
### Steps to Solve:
Added metadata to `index.html` head, as well as updated the `favicon.ico` and linked it in the metadata.
```
<link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
    <!-- HTML Meta Tags -->
    <meta name="description" content="Horizons, a gallery of our universe."/>
    <meta name="keywords"content="Horizons, gallery, universe, NASA, APOD, astronomy, planets, space, cosmos, astronomy photos, NASA APOD, Astronomy Picture of the Day">
    <!-- Facebook Meta Tags -->
    <meta property="og:url" content="horizons.jaydeninniss.com"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="Horizons"/>
    <meta property="og:description"
        content="Horizons is an online image gallery of our universe that shows new photos and information every visit. Embark and explore our universe!"/>
    <meta property="og:image" content="%PUBLIC_URL%/og-image.jpg"/>
    <!-- Twitter Meta Tags -->
    <meta name="twitter:card" content="summary_large_image"/>
    <meta property="twitter:domain" content="horizons.jaydeninniss.com"/>
    <meta property="twitter:url" content="%PUBLIC_URL%"/>
    <meta name="twitter:title" content="Horizons"/>
    <meta name="twitter:description"
        content="Horizons is an online image gallery of our universe that shows new photos and information every visit. Embark and explore our universe!"/>
    <meta name="twitter:image" content="%PUBLIC_URL%/og-image.jpg"/>
```
