### ISSUE TITLE
Back to Top - Jumps Harshly

### ISSUE THREAD

**Issue by jaydeninniss** [ssupix/horizons-api#16]
### Steps To Reproduce:

1. Scroll down the page
2. Click the back-to-top button
3. Notice how jarring the scroll back to the top is!

### Expected Result:
The scroll is smooth as it auto-scrolls the user back to the top.

### Actual Result:
The scroll is not smooth as it scrolls the user to the top of the page.

### Configuration:
Tested on a Macbook Pro 16"
Chromium Based Browser
December 6, 2024, 12:00pm

Severity: Medium
Priority: Medium
Type: Bug
Branch: development

**Comment by ssupix** [comment]
html {
    scroll-behavior: smooth;
}
