### ISSUE TITLE
Overflow on Header Needs to Be Hidden

### ISSUE THREAD

**Issue by jaydeninniss** [ssupix/horizons-api#8]
### Description: 
Header content has overflow issues that need to be hidden.

### Steps To Reproduce:
1. Navigate to the Home Page.
2. Scroll to the left and right.

### Expected Result:
The page remains solid and does not scroll past the main content.

![Screenshot 2024-12-06 at 6 40 56 PM](https://github.com/user-attachments/assets/b45b94ee-ec6c-4c24-9900-c5b84360a149)
When scrolled to the right (shouldn't be allowed)

### Actual Result:
Overflow is visible on the right edge when scrolling left or right.

![Screenshot 2024-12-06 at 6 41 02 PM](https://github.com/user-attachments/assets/014aef51-d749-4753-a26f-f81e213ff3b2)
When scrolled to the left (expected result)

### Configuration:
Tested on a Macbook Pro 16"
Chromium Based Browser
December 6, 2024, 12:00pm

Severity: Medium
Priority: High
Type: Bug
Branch: header

**Comment by ssupix** [comment]
oveflow-hidden class on header wrapper
