### ISSUE TITLE
Visible Scroll Bars on Entire Site

### ISSUE THREAD

**Issue by jaydeninniss** [ssupix/horizons-api#9]
### Description: 
Scroll bars appear unnecessarily across the site.

### Steps To Reproduce:

1. Navigate to the website.
2. Scroll up/down. Pay attention to the right side of the screen.

### Expected Result:
The page does not show scroll bars at the edges when scrolling.

### Actual Result:
Scroll bars are visible on the edges of the site when scrolling.

### Configuration:
Tested on a Macbook Pro 16"
Chromium Based Browser
December 6, 2024, 12:00pm

Severity: Medium
Priority: Medium
Type: Bug
Branch: development

**Comment by ssupix** [comment]
* {
    scrollbar-width: none;
}
